### ISSUE TITLE
Cannot access results in coffeescript jasmine tests

### ISSUE THREAD

**Issue by tanepiper** [webBoxio/atom-hashrocket#1]
Code example:

    subject = "hello World"
    #=> subject result hello World

    describe ".helloText", ->

      Given ->
        @subject = "Hello, World"
        #=> @subject result unreachable
      Then ->
        expect @subject
        .toEqual "Hello World!" #=>

I'm using https://github.com/searls/jasmine-given as the DSL here, to output specs.

I like the look of this library as a tool to help scaffold test files with some basic data padding that can easily be moved.

As you can see I want the result of setting a value to check, but I get unreachable which is a good code smell - but really I should get that result back as given the Given, Then, etc are code blocks so it should be returned for the debug output.

I think this library is excellent, but it's not a test framework. It's a very good scaffolding tool and code smell tester. I wonder if I can also automate some of this stuff :)

**Comment by ChanceM** [comment]
@tanepiper The reason you get unreachable is that in order for the variable to have a value the CoffeeScript is compiled and then run using node. So the Jasmine and Jasmine-Given functions are returned as not defined thus they cannot be executed. See working example below.

```coffeescript
subject = "hello World"
#=> subject result hello World

describe = (value, callback) ->
  callback()

Given = (callback) ->
  callback()

Then = (callback) ->
  callback()

expect = (value) ->
  value
toEqual = (value) ->
  

describe ".helloText", ->

  Given ->
    @subject = "Hello, World"
    #=> @subject result Hello, World
  Then ->
    expect @subject
    .toEqual "Hello World!" #=>

```
